pipeline:
  build:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build -t immanuelpotter/example-webserver .
  test:
    image: docker
    volumes:
      - /var/run/docker.sock/var/run/docker.sock
    commands:
      - docker run immanuelpotter/example-webserver /test.sh
